language: node_js
node_js:
  - "8"
  - 'stable'
  - 'lts/*'
after_success:
  - npm run coverage
services:
  - docker

before_script:
  - docker  build -t sshd ./test
  - docker run -p 127.0.0.1:22:4567
  - docker ps -a
