# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.ssh.insert_key = false
  config.vm.network :forwarded_port, host: 2022, guest: 2022
  config.vm.synced_folder "./", "/vagrant", type: "rsync", disable: "true", rsync__exclude: [".git/"], rsync__args: ["--verbose", "--archive", "--compress", "--copy-unsafe-links"]
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "4096"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "./site.yml"
  end
end
